enginesearch/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('custreg/', views.custreg, name='custreg'),
    path('products/', views.products, name='products'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('add_product', views.add_product, name='add_products'),
    path('profile/', views.profile, name = 'profile'),

    ]

enginesearch/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

enginesearch/enginesearch/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from account.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^index/$', home),
    #url(r'^$', lan),
    url(r'^prodform/$', products,name='productform'),
    url(r'^register/$', custreg, name='register'),
    url(r'^login/$', login, name='login'),
    path('cart/', include('cart.urls')),
    url(r'^logout/$', logout,name='logout'),
    path('index/', include('shop.urls', namespace = 'shop')),
    path('account/', include('account.urls', namespace = 'account')),
    path('', include('landingpage.urls', namespace = 'landingpage')),
	path('search/', include('search.urls', namespace ='search')),
	
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

enginesearch/landingpage/urls.py
from django.urls import path
from . import views

app_name = 'landingpage'

urlpatterns = [
    path('', views.landingpage, name='landingpage')
]

enginesearch/search/urls.py
from django.conf.urls import url

from search.views import *

app_name='search'

urlpatterns = [
	url(r'', search, name='search'),
	]

enginesearch/shop/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from .views import product_detail, product_list

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    path('/account/', include('account.urls')),
]

enginesearch/search/models.py
from django.db import models

# Create your models here.

enginesearch/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True, null=True, blank=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    rating = models.PositiveIntegerField(default=0)
    url = models.CharField(max_length=100, default="www.exampleurl.com")

    class Meta:
        ordering = ('rating',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, db_index=True, null=True, blank=True)
    slug = models.SlugField(max_length=100, db_index=True, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    available = models.NullBooleanField(default=True, null=True)
    stock = models.PositiveIntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        if self.name==None:
         return "ERROR-CUSTOMER NAME IS NULL"
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


class Mixture(models.Model):
    name = models.CharField(max_length=100, db_index=True, null=True, blank=True)
    slug = models.SlugField(max_length=100, db_index=True, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    #available = models.NullBooleanField(default=False, null=True)
    stock = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

enginesearch/shop/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.core.validators import validate_email

class products_form(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Which part?:'}), required=True, max_length=50)
    stock = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'How many do you have?:'}), required=True, max_length=50)
    price = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter rate:'}), required=True, max_length=50)


    class Meta():
        model = products
        fields = ['name', 'stock', 'price']

enginesearch/search/views.py
from django.shortcuts import render
from search.documents import MixtureDocument


# Create your views here.
def search(request):
	q = request.GET.get('q')
	
	if q:
		mixtures = MixtureDocument.search().query("match", name = q)
	else:
		mixtures = ''
		
	return render(request, 'search/search.html', {'mixtures':mixtures})

enginesearch/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.db.models import Q
from .config import pagination
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpRequest, HttpResponseRedirect
from django.db.models import Count

app_name = 'shop'

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    query = request.GET.get('q')
    if query=='':
        return HttpResponseRedirect('/')
    if query:
        categories = Category.objects.filter(Q(slug__icontains=query)| Q(url__icontains=query))
    
    
    #if query:     
        products = Product.objects.filter(Q(slug__icontains=query) | Q(category__name__icontains=query) | Q(description__icontains=query))
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)
	
    categories_counter = products.annotate(Count('id'))
    categories_count = len(categories_counter)

    context = {
        'category': category,
        'categories': categories,
        'products': products,
		'categories_count':categories_count,
		'query':query,
    }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

enginesearch/shop/templates/shop/add_product.html
<form method="POST" action="" >
{% csrf_token %}
<div class="form-group">
	<label for="name">User-name</label>
	{{ form.username}}
	{{ form.username.errors }}
</div>

<div class="form-group">
	<label for="email">Email</label>
	{{ form.email}}
	{{ form.email.errors }}
</div>
 
<div class="form-group">
	<label for="First-Name">First-Name</label>
  {{ form.first_name}}
</div>

<div class="form-group">
	<label for="lastname">Last-Name</label>
	{{ form.last_name}}
</div>

<div class="form-group">
	<label for="password">Password</label>
	{{ form.password}}
</div>

<div class="form-group">
	<label for="password">Confirm-Password</label>
	{{ form.confirm_password}}
	{{ form.confirm_password.errors }}
</div>
<div>
<button class="btn btn-primary btn-block"  type="submit">Submit</button>
</div>

</form>

enginesearch/shop/templates/shop/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}SELCOUTH{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
	<link rel="stylesheet" href="{% static 'css/my-login.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body class="my-login-page">
{% include 'shop/navbar.html' %}

{% block content %}


{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

enginesearch/shop/templates/shop/navbar.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
      <div class="navbar-header">
    <a href="{% url 'landingpage:landingpage' %}" class="navbar-left" > <img src="{% static 'img/logo.png'%}" width="130px" height="55px"> </a>
  </div>
  <form class="navbar-form navbar-left">
      <div class="input-group">
          <input type = 'text' class="form-control" name = 'q' value = "{{request.GET.q}}" placeholder = "search">
		  
          <div class="input-group-btn">
          <button class="btn btn-primary" type="submit">
            <i class="glyphicon glyphicon-search">Search</i>
          </button>
        </div>
      </div>
  </form>
	
		 {% if request.user.is_authenticated %}
			<ul class="nav navbar-nav navbar-right">	
		    <li><a href="/account/profile"><span class="glyphicon glyphicon-user"></span><b><big>{{request.user.username}}</big></b></a></li>
			<li><a href="/account/add_product"><span class="glyphicon glyphicon-plus"></span><b>Add Products</b></a></li>
			<li><a href="{% url 'account:logout'%}"><span class="glyphicon glyphicon-log-out"></span><b>Logout</b></a></li>
			</ul>
         {% else %}
			<ul class="nav navbar-nav navbar-right">
			<li><a href="{% url 'account:login'%}"><span class="glyphicon glyphicon-log-in"></span><b>Sign In</b></a></li>
			<li><a href="{% url 'account:custreg'%}"><span class="glyphicon glyphicon-user"><b>Register</b></a></li>
			</ul>
         {% endif %}
     
  </div>
</nav>

enginesearch/shop/templates/shop/search.html
{% extends "base.html" %}
{% block title %}Search{% endblock %}

{% block content %} 
 {% if "query" in request.GET %}   
 <h1>Posts containing "{{ cd.query }}"</h1>  
 <h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>  
 {% for result in results %}   
 {% with post=result.object %}       
 <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}
 </a></h4>
 {{ post.body|truncatewords:5 }}  
 {% endwith %}    {
 % empty %}
      <p>There are no results for your query.</p>
	  {% endfor %}  
	  <p><a href="{% url "blog:post_search" %}">Search again</a></p> 
	  {% else %}  
	  <h1>Search for posts</h1>  
	  <form action="." method="get">     
	  {{ form.as_p }}    
	  <input type="submit" value="Search">   
	  </form> 
	  {% endif %} 
	  {% endblock %}