enginesearch/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('custreg/', views.custreg, name='custreg'),
    path('products/', views.products, name='products'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('add_product', views.add_product, name='add_products'),
    path('profile/', views.profile, name = 'profile'),

    ]

enginesearch/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

enginesearch/enginesearch/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from account.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^index/$', home),
    #url(r'^$', lan),
    url(r'^prodform/$', products,name='productform'),
    url(r'^register/$', custreg, name='register'),
    url(r'^login/$', login, name='login'),
    path('cart/', include('cart.urls')),
    url(r'^logout/$', logout,name='logout'),
    path('index/', include('shop.urls', namespace = 'shop')),
    path('account/', include('account.urls', namespace = 'account')),
    path('', include('landingpage.urls', namespace = 'landingpage')),
	path('search/', include('search.urls', namespace ='search')),
	
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

enginesearch/shop/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from .views import product_detail, product_list

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    path('/account/', include('account.urls')),
]

enginesearch/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True, null=True, blank=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    rating = models.PositiveIntegerField(default=0)
    url = models.CharField(max_length=100, default="www.exampleurl.com")

    class Meta:
        ordering = ('rating',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, db_index=True, null=True, blank=True)
    slug = models.SlugField(max_length=100, db_index=True, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    available = models.NullBooleanField(default=True, null=True)
    stock = models.PositiveIntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        if self.name==None:
         return "ERROR-CUSTOMER NAME IS NULL"
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


class Mixture(models.Model):
    name = models.CharField(max_length=100, db_index=True, null=True, blank=True)
    slug = models.SlugField(max_length=100, db_index=True, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    #available = models.NullBooleanField(default=False, null=True)
    stock = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

enginesearch/shop/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.core.validators import validate_email

class products_form(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Which part?:'}), required=True, max_length=50)
    stock = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'How many do you have?:'}), required=True, max_length=50)
    price = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter rate:'}), required=True, max_length=50)


    class Meta():
        model = products
        fields = ['name', 'stock', 'price']

enginesearch/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.db.models import Q
from .config import pagination
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpRequest, HttpResponseRedirect
from django.db.models import Count

app_name = 'shop'

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    query = request.GET.get('q')
    if query=='':
        return HttpResponseRedirect('/')
    if query:
        categories = Category.objects.filter(Q(slug__icontains=query)| Q(url__icontains=query))
    
    
    #if query:     
        products = Product.objects.filter(Q(slug__icontains=query) | Q(category__name__icontains=query) | Q(description__icontains=query))
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)
	
    categories_counter = products.annotate(Count('id'))
    categories_count = len(categories_counter)

    context = {
        'category': category,
        'categories': categories,
        'products': products,
		'categories_count':categories_count,
		'query':query,
    }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

enginesearch/shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
   <div class="container">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                <div class="card">
                    <div class="card-body">
                        <div class="col-md-6 text-right">
                            <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 170px; width: auto">
                        </div>
                        <div class="col-md-6" style="padding-left: 20px">
                            <h3>{{ product.name }}</h3>
                            <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>
                            <p class="text-muted">Rs. {{ product.price }}</p>
							
                           <!-- <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {% csrf_token %}
                                {{ cart_product_form }}
                                <input type="submit" value="add to cart" class="btn btn-primary">
                            </form>-->
                            <p>{{ product.description|safe|linebreaksbr }}</p>
                        </div>
                    </div>
                </div>
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->
      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}

enginesearch/shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}

{% load static %}

{% block title %}
	{{query}}
{% endblock %}

{% block content %}


<div class="container-fluid">
	
	</form>

   
      <div class="row" style="padding-top: 4%; padding-left: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
					{%if categories_count == 0 %}
					<p style= "padding-left: 10px"><small><em><b>Sorry, No results Found! Try: engine, engine oil.</b></em> </small></p>
					{%else%}
					<p style= "padding-left: 10px" ><small><em><b> {{categories_count}} Results found:</b></em> </small></p>
					{%endif%}
                  {% for product in products %}
                      <div class="col-md-8">
                        <div>
                           <!-- <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                            </a>-->
                            <div class="list-group">
                                <h2 class="text-left">
                                    <a href="{{ product.category.get_absolute_url }}"><b>{{ product.category }}</b></a>
                                </h2>
                                <h3><p class ="text-left"><a href="{{ product.get_absolute_url }}"><b>{{ product.name }}</b></a></p></h3>
                                <p class ="text-left"><a href="{{product.get_absolute_url}}"><em>{{product.category.url}}</em></a></p>
								<p class ="text-left" style="padding-bottom: 0px;;" >{{product.description}}</p>
								<a class= "text-left" href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." href = "account:product_detail" style="height: 80px; width: auto">
                            </a><br>
								<a class ="text-left"><a href="#"><b> Rating:{{product.category.rating}}/5</b> </a> 
								<a class="space"><b> $ {{ product.price }}</b></a>
								
								{% if request.user.is_authenticated %}
								<a href="#" data-toggle="modal" data-target="#myModal" class="space"><b> ✉ Message <!--$ {{ product.message }}--></b></a>
								  <div class="modal fade" id="myModal" role="dialog">
									<div class="modal-dialog modal-lg">
									  <div class="modal-content">
										<div class="modal-header">
										  <button type="button" class="close" data-dismiss="modal">&times;</button>
										  <h4 class="modal-title">✉ Message</h4>
										</div>
										<div class="modal-body">
										<form method="post">
											<textarea rows="4" cols="100" name="message" placeholder="Write your message here">Hi,
											</textarea>
                                        </form>
										</div>
										<div class="modal-footer">
										  <a href="#" class="btn btn-default" type="submit"data-dismiss="modal">Send</a>
										  </form>
										</div>
									  </div>
									</div>
								  </div>
							
								{% else %}
								<a href="#" data-toggle="modal" data-target="#myModal" class="space"><b>✉ Message <!--$ {{ product.message }}--></b></p>
								  <div class="modal fade" id="myModal" role="dialog">
									<div class="modal-dialog">
									
									  <!-- Modal content-->
									  <div class="modal-content">
										<div class="modal-header">
										  <h4 class="modal-title">Selcouth account required</h4>
										</div>
										<div class="modal-body">
										  <p>You need to sign-in to send a message.</p>
										</div>
										<div class="modal-footer">
										<a href="{% url 'account:login'%}" class="btn btn-default">Log-in</a>
										<a href="{% url 'account:custreg'%}" class="btn btn-default">register</a>
										</div>
									  </div>
									  
									</div>
								  </div>
								 
								{% endif %}
								<hr>
								    <!--{% endfor %}-->
					<!--{%if categories%}
					
					<h2><a>Companies lists:</a></H2><br><br>
				    {% for category in categories %}
                      <div class="col-md-8">
                        <div class="list">
                            <div class="list-group">
                                <h3 class="text-left">
                                    <a href="{{ product.get_absolute_url }}">{{ category.name }}</a>
                                </h3>
                                <a href="<p class="text-left">{{ category.url }}</a></p>
                            </div>
                        </div>
                      </div>
                  {% endfor %}
				  {%endif%}
			  </div>
			  </div>
				
-->
          </div><!-- /.blog-post -->
			
                  </a>
        </div><!-- /.blog-main-->

        <!--<div class="col-sm-3 col-sm-offset-1 blog-sidebar" style="padding:0px; margin: 20px;">
		<div class="thumbnail" style="border="5px;">
          <div class="sidebar-module">
            <h4>Categories</h4>
            <ol class="list-unstyled">
              <li {% if not category %} class="active"{% endif %}><a href="{% url 'shop:product_list' %}">All</a></li>
            {% for c in categories %}

              <li {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
            </ol>
          </div>
        </div>--><!-- /.blog-sidebar -->

      </div><!-- /.row -->
	  
	  </div>

    </div><!-- /.container -->

{% endblock %}